### ISSUE TITLE
How to run your code?

### ISSUE THREAD

**Issue by JafferWilson** [Sardhendu/License-Plate-Detection#1]
Hello,
Please can you add the information of how to run the code? Even, please do share some example datasets that will help in understanding the type of input to be given to the system for training.

**Comment by Sardhendu** [comment]
Hi Jaffer,

I have updated the readme.md file and added sample data set. 

You have to create directories as indicated in the config-local.conf file, and load the training and validation data. Finally to run the code you just have run the LP_Detect_main.py file.

You many wanna look at the below three important files.

1. config-local.conf
2. configurations.py
3. LP_Detect_main.py
